id = "targino-theme"
name = "Targino Theme"
schema_version = 1
version = "0.1.0"
authors = ["Vallahor <vallahor91@gmail.com>"]
description = "A theme for the Zed text editor based/modified from the Visual Studio Code theme Gruvball."
repository = "https://github.com/vallahor/targino-zed"
